#!/bin/bash
set -x

#link to the debian folder structure
SUBMODULE_SRC1=https://salsa.debian.org/go-team/packages/golang-github-docker-distribution/-/archive/debian/2.7.1+ds2-7/golang-github-docker-distribution-debian-2.7.1+ds2-7.tar.bz2
#link to source files
SUBMODULE_SRC2=https://github.com/docker/distribution/archive/v2.7.1.tar.gz


PKG_BUILD_NAME=$1
mkdir ${PKG_BUILD_NAME}
pushd ${PKG_BUILD_NAME}

PKG=golang-github-docker-distribution-debian-2.7.1+ds2-7.tar.bz2
wget $SUBMODULE_SRC1 -O $PKG
tar --bzip2 -xvf $PKG --strip-components 1

PKG=v2.7.1.tar.gz
wget $SUBMODULE_SRC2 -O $PKG
tar -xvzf $PKG --strip-components 1
