---
debname: flux2
debver: 2.8.4-0
src_path: files
dl_files:
  flux_2.8.4_linux_amd64.tar.gz:
    topdir: null
    url: https://github.com/fluxcd/flux2/releases/download/v2.8.4/flux_2.8.4_linux_amd64.tar.gz
    sha256sum: 9fc331d8f02bf292fad8060e94109f4608226f20f3b750b2f704251a4bbdfde9

revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
