#! /bin/bash
#
# Copyright (c) 2013-2014 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#


#echo "defaults: $1-$2-$3-$4"

if [ -z ${1} ] ; then
    basedir=/scratch
else
    basedir=$1
fi

if [ -z ${2} ] ; then
    extradir=$basedir/var/extra
else
    extradir=$2
fi

if [ -z ${3} ] ; then
    hostname=$HOSTNAME
else
    hostname=$3
fi

mkdir -p ${extradir}
