#!/bin/bash
#
# Copyright (c) 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Remove stale shadow lockfiles
#

rm -f /etc/gshadow.lock /etc/shadow.lock /etc/passwd.lock /etc/group.lock

