---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - integ-tox-pep8
        - integ-tox-linters
        - integ-tox-pylint
    gate:
      jobs:
        - integ-tox-pep8
        - integ-tox-linters
        - integ-tox-pylint
    post:
      jobs:
        - stx-integ-upload-git-mirror

# This is the common base job definition for StarlingX flock services
- job:
    name: flock-devstack-base
    parent: devstack
    description: |
      Base job for StarlingX Flock components DevStack tests
    nodeset: debian-bullseye
    roles:
      - zuul: openstack/devstack
    timeout: 9000
    required-projects:
      - name: openstack/devstack
      - name: openstack/keystone
      - name: openstack/requirements
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
        # Database
        mysql: false
        postgresql: true
      devstack_localrc:
        # LIBS_FROM_GIT: keystone
        FORCE: yes  # yamllint disable-line rule:truthy

# A minimal base job that eliminates most OpenStack services
# Leave Celiometer, Horizon and Swift in the base since none
# of our jobs need them.
- job:
    name: flock-devstack-base-min
    parent: flock-devstack-base
    timeout: 7800
    vars:
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false

# An equivalent tox-based functional test job to flock-devstack-base
- job:
    name: flock-devstack-tox-base
    parent: devstack-tox-functional
    description: |
      Base job for StarlingX Flock components DevStack tests that use tox
    nodeset: debian-bullseye
    roles:
      - zuul: openstack/devstack
    timeout: 9000
    required-projects:
      - name: openstack/devstack
      - name: openstack/keystone
      - name: openstack/requirements
    vars:
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        horizon: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        tempest: false
        # Database
        mysql: false
        postgresql: true
      devstack_localrc:
        # LIBS_FROM_GIT: keystone
        FORCE: yes  # yamllint disable-line rule:truthy

# And the tox version of the base-min job
- job:
    name: flock-devstack-tox-base-min
    parent: flock-devstack-tox-base
    timeout: 7800
    vars:
      devstack_services:
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false

- job:
    name: integ-tox-linters
    parent: openstack-tox-linters
    description: |
      Run linters
    nodeset: debian-bullseye

- job:
    name: integ-tox-pep8
    parent: openstack-tox-pep8
    description: |
      Check conformance with pep8
    nodeset: debian-bullseye

- job:
    name: integ-tox-pylint
    parent: tox
    description: |
      Tox-based job with a minimal functional target in tox.ini
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
    vars:
      tox_envlist: pylint
      tox_extra_args: -c tox.ini

- job:
    name: stx-integ-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/integ to
      github.com/starlingx/integ
    vars:
      git_mirror_repository: starlingx/integ
    secrets:
      - name: git_mirror_credentials
        secret: stx-integ-github-secret3
        pass-to-parent: true

- secret:
    name: stx-integ-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - GWRL8t1TcZ6C5B8cBoqKQHT3TcaCPj1aCpo/2274RUNYxfqEs9OQbQ/fKK9rI3h9XVhaz
          9J55KNnL82EJlYFvxpqGaRnKAt3rL7zd3wbkf8MrDCLAPb3thBkeLWdEudEaPhS+hCyOe
          +cGrqqsLzoXb30LahRHnfFvkhU+cOC3oTvkX6XjcLjo8Fsqwv0+io0Bz3d91ZbMKWfsTK
          xakbWo47cfAgJ878edL6rUlnXzQiYF0h3MrVtu3/kuQoV2xxwqCeXDXzqALbWTSMM66En
          Jctl2zLbmxQ4pASYZMGg9C1FAINXzJW+Qb8GLAa6AU4inQKoPyI0p4IYzadHjIZrxCfZj
          lQx7pdj2Pu0DNeTDgzC3sbGTNgGJLmHrltg7ki9PzOhB41lJlTgMUJIwvC9V/9SLmT3yi
          tLJhAkcuJ8UlRAaheM7umGtGoHD7rk5GwgHWC5lwT8jUNiFY1SQG5hhIg0a7vVcZE2h+f
          9LGaJhZsQYEFNP0DR5+bDCDtWtcCxF0UqEDDuZx6DTi0u32BeLsKwS3t9BSw+Jj2kJ4Kn
          80oJoWjMlEeABxRc1Qb5ASOQFv+9lR3d6+A9fLPauzMZ+dnUPNEnfAOHg2TjiJD8ljvmM
          jX6ckk6zlT7MM7mLqEBfJTerBIPZR3ZPP8jihgIaLIUjAKRSqrmFScKYsrJmpw=
        - f8ljAoYOpeeamwSKNmc9g7NIvoF+45MTfDD1Y1bfCuQqsHgitdjsrhgfUUZjDtFcd7Lrb
          Rc7sOeOOnnIWivoixlwZjtd6YeZLoVAE39TW+GXHoFpz84msMBWbQKKX91AQ5aHFQgAOl
          nNRpqm5p8k6kDPXQMvvR5v378ZvMU834MOwAd2FkiLis+R+ApBTTpDKkApklmai6rqoP1
          FtZhc1AOG3uCx2rTAZKeDeOK7pid+GGGNnmnW2MScB5qkCfeOqX7DZ2jHpr2orvXr3ibh
          cCfV+H8ka/uRJAk9n9gL419BK6DfwSrMqUx9j9+VP8efXXfq++3VSUE99nIjCDWd6tain
          ZQx1GaRlTA04uBwmPooyiOFZKFtvraBxZOV99W3VJQet3IjY9x1m1bOk2WM/LPwEmEgZx
          QNR2lnIM8u54VWZSL5dL/QxXFv6YqQ2gpcJeQ2m3+pF8Nr3tYg96yL2AlWBIC2OE0VyVp
          134TLR6IQEoPf8lSsP9JU8rz+Sg9FBdWmT8abjd1oZ8J0FfNCeW5KlBxTL9Jau7HLQJZN
          AtpVgN0EbrM04vuzt2M4xZpRjp1T78gn7yIH9mrsdnU0qKqdTUu9Z/JKp65frPnU6YAMJ
          ItAtVT3azFUMCcxMxvxR2DFqwJl4HlMnJMq4GJkPD9T5sJ7/cemyadFVFENIrY=
        - nYmI+RymJQK3bIqsI4SIEgjHWlJGl3PMnNOX9P66tAFaspJPPYxRgqR2Ik2xcNyieR6nR
          dOwu6syPS8qYMy7lYLWl1+BGhesdCo6w6ajLUMm+8RdVvIDyA2umi6wueUA+ew+Bv8eh2
          qS/jGMcehZQw4hAp5SFCFqeToCpNEjmJet6DlLllHK/clOa4Ztiq9jF4Y2YoRUvhF/NiZ
          4gMpF6evCITh7n7LPwVKiAQx8a6MCk3QMDGR2T4S9QQWVE+8ytLLXm5P9xJomewIJNxVI
          sdOXe9dVjSLJI2sKK7gKtn+SKRfvCnLbxUUvlGeMrJX5NUdW2uu13CPiVcMqQs5EZ6UiN
          uUeWNk7nWsu8Na2GDYuOhlZfmJyxogyTfeeIjTW3NkABS88V1tKGZ7Z9PmJLrPuICPLBq
          HTmwhnOUTFpx4cB9eeaDP9eWSTzesrqVg670XhNL2gqrBiwtxbMfmAPObY5YwmNlVQpWf
          eKhYCRH8kA7/RrB0RRV9vPNuJiI/JhvtEbRZkmIxlDRu4BgBZpHv3agzgC/g5BleAKtUW
          K3wBp2Y4tp2X3+h4GNg/v9LCBmWp23erlgZnwsrPPZ4AEeEV8EvZxPM11PvozRaD7OdL5
          d2Yga6tORMiQ/L9HfiTIG0d/M6ZrO4PC7Ye+hHnY8mfM7IR+RBW3+G9KLDbXtA=
        - RLjcbQBvQr+dgkhNpPOGit4/wGUD6agiJoDVeDEqTaYOTBE4ukhcEFCIyz1diU0EFGZ6x
          GjpiPMO+ke/i/m5TqTQnSGQu8jxoT6UrGuC5JcSV4mPPMIkhzrAw202pqemikefLeo9nV
          kFsuqwYyOBJ4Ur1QU9+mLchLoRvK47ybhvkfd5VROE9IW1kSvgE22+FnSGvz9Rkd837BF
          2mjm1unrXPwcXWOZJQxkTFjK4p44OvK+g2Li3ldEQzPij7YyECGbCH9/oVvVHnKL611r/
          yFC8XjiQSd2TJvreW0s7/kdGmDH7X288K8TExTzgCoatJfMDrg+mjJUhRe85d5d+gW72u
          V2JnzWVN78Tp1XV2WA0TCFcVeH+7htckSGBN+Ay63DrIreRIZskQGnrUS4o4TIQ78TsKP
          7qLEfJyjoh44D18mwMK7clzzgpo1LyXBiZmF9n+dcqEwEqONm3a0hGYWNoESOZ52NWI/y
          VSpnfjmZ5pT6xNbFpAbUWB9h2jJgrH40okydxZvPbCTl7gZPcOfOtfs4Zf/clz1X3pPkL
          tKo7VmEHiJhzpR7YlDNBxcpuirKP1Ifog1GgzpV9ZdIrVvLT4jOtIyu4OofF2P2Q9r/Ep
          M5yRYy+Ka9S93oI4QvIHt5TeQigzkx82vDmBnlyg8cyPwKIOEjRhPWHRFg7pDQ=
        - PGcRPyc7cOhFkjCpsZ/BZUJoTYwahGGTC3v7IShoifm12/CyZe0/mAGfdxbzeHEQWEVm5
          fpCjTk3e0fpew9xv8tdDgT3qSC5ttGYTXrf1K/89NFDjFu1qq2uTYba/okpOH2x0T5CD8
          MzkcnCKU315/eLwU5FXi4Zngw/eZXJ6RAg8WlsGyzWcpUYLMTQ4Snilvushc+AJh6t22f
          W9pEfb3zhSPOuhUrKaBTWyiZqAixjY0uplFIi8aKTqqajEeDQ1PoJtz8UPoTbW7VvKhVT
          bmiY9hUy5pPAStlaGuLVNFUN1Veytw+4U5nmXzGg80wl1QlJQG5W5HmM98v0vRfSCUqVM
          BExUdr+dMAaQjnkIEq/KE+F+zYauUR44DyKS/RmHqGsx7z49J+yeoNmoR+SRFjJFyf/Tw
          Y1TccGkjEMok0AfaJ1Gr0juWyAIJqUfwTHW1GvCgHmGZMkeF9jZdkEQ8j9Zb4NM77f2zB
          bYVof5+sk7i6cYWCTcbIMOL9xchLuCHPi/ckhORfFAJYYKW8mCYm7bkHxf8UmQdWig4LK
          LwDE1OSNz6rJQwj/Chs+jO2sqbT/zthlIgi02PK0C2OlThn4guFzZbcbVJXucXTNis6v8
          UDeAltTRrCvN00B96DZ+e93WQY/0XFDXJjKfierZ2HtQ6bdlxjV+wgfLTlq1c0=
        - ruRt/jw5FmBCWbTlnlBxP8hllgrchkwtAe2F/UGMwYPz/0SJ/7MCi1EpOJFmhkUyFG9oV
          XpVFULP5dtLO7I9A7h0ObOFANF8wk4kG/NzQa+fjh4p76g4E55vYZPokBzoLYt/R8p3Ca
          +NsYEwyNd/ppjBAqxjvtvKJXmVfoDqNE7sMR89rLbolzA/bVoA6aF5Nmtw3iE/Y1DRFrE
          V40V1DyGodnc0/QG3mzp8rsxGgzRVmk+PYflcGytGIIgZV56iBeOsr5W+BFlUq3ijOnsu
          0AKnmUgaCgrQP65LQcZfqOZri7CJS1ed4Z3fPLObI+tOWYC1wXUU09Uiead8pHTaybi80
          SuJHUofGbt2A1ZbCoR+RVM01xbsyZBasfyPlbSPsemVUBAAm8nRgjDt4aH5wYc/e6Tgo+
          dpZsKYI92XjUW47TILy6e8P3sWdnnh8+8PPWKdfg2yDRJr+8olZxoiAECG7sAC6mpEfbb
          YjwYrYACSxpk/DhMFkGLyvwY8mPPWc6Sq+OpT5ogL+tULQJWH3Z+Ocz8AbYwZgQLAduv8
          Rg1+Hq88zA9RIil5JZz/DVjtTz1PDHRWHFg3EITuc4iDKn27wjvNwpn5usCHBD6Y+jTXo
          M/xpNenMjgGd1XGFkmg2uFDfINZeXc46kvjySlKRNjVGzYswTUBDXADq58uxpM=
        - p1xblZ/GQIv6LX7T3mEMWj2E8CLS0rWoBORe+r7QRB9dnnfxJ8vkWeESSBfyT7qMg7dZC
          SscEghpD6c3HD55xvbIJHvFQv2KN7WCQgqHYdDHFZcetsrOz7Sfgq61zQVeQSKo5BiAiO
          RWkhVKWVR2iQuJdEhW32Zv5dBtF6paGXdP6ngaoOHGohEw2NoyO9pHakPhPSvKdeblTC9
          QGVGEroQ0DsYO26mu8ACjeedR3t2lb6d+1Yvg8qm2NvX6w3Qa1nh+aKIN0ikWp9N2HfS0
          68p6+cUCHpbWxRdZWzM+1srUDJdHc4+dfCpFaavGT4NIGwjkg/o8r4xskQSXJ/XWWlHVX
          7uEL4HtONQUXL/2m3SA0+/P23gjD3sSPhBJPLdvAaXJSGsMq+w/qK6/BNzzC+/GxVOCdJ
          PyLNaP250vyztiqxmorjgYyKEaH3csjtO8JSqTv3LsNGU2ybyCr1FQ1d7gmRnwJGgALqF
          aL9QDu38+Ioa1Vth9Np0zQt6+/qMZeQNxCwN0pkWglw3/IT26WCBdM27ndDT88/jrlYTT
          v5QrXWHJ1ssxjJEVpRIhszLwGopAZvH6Apio9zmjge1vLTrujGCF1dknmML5Tvk4IVQqc
          KELkHvGlRSkdcEwPWbKmPGGLlb/Xo1cWX9PyRbvBRGXa7e1dYPqorSvrdh07ik=
