# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#



# qemu-kvm-ev
qemu-kvm-ev
qemu-img-ev
qemu-kvm-tools-ev


# libvirt
libvirt
libvirt-docs
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-config-nwfilter
libvirt-daemon-driver-network
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage
libvirt-daemon-driver-qemu
libvirt-daemon-driver-lxc
libvirt-client


# python-ryu
python2-ryu
python-ryu-common

# python-smartpm
python-smartpm

# lldpd
lldpd




# tss2
tss2


# libtpms
libtpms

# swtpm
swtpm
swtpm-cuse
swtpm-tools


# python-3parclient
python-3parclient

# python-lefthandclient
python-lefthandclient



# docker-distribution
docker-distribution

# helm
helm







# e1000e-kmod
kmod-e1000e
kmod-e1000e-rt

# i40e-kmod
kmod-i40e
kmod-i40e-rt

# i40evf-kmod
kmod-i40evf
kmod-i40evf-rt

# ixgbevf-kmod
kmod-ixgbevf
kmod-ixgbevf-rt

# ixgbe-kmod
kmod-ixgbe
kmod-ixgbe-rt

# qat17
qat17
qat17-rt

# tpm-kmod
kmod-tpm
kmod-tpm-rt

# integrity-kmod
kmod-integrity
kmod-integrity-rt

# drbd-kernel
kmod-drbd
kmod-drbd-rt

# rpm
rpm-plugin-systemd-inhibit

# dpkg
dpkg

# cgcs-users
cgcs-users

# ldapscripts
ldapscripts

# drbd
drbd
drbd-utils
drbd-udev
drbd-pacemaker
drbd-heartbeat
drbd-bash-completion


# initscripts
initscripts

# setup
setup

# nss-pam-ldapd
nss-pam-ldapd


# nfs-utils series package

# dhcp
dhcp
dhclient

# openssh
openssh
openssh-clients
openssh-server

# facter
facter

# vim
vim-enhanced

# python
python

# libvirt-python
python2-libvirt

# lighttpd
lighttpd
lighttpd-fastcgi
lighttpd-mod_geoip
lighttpd-mod_mysql_vhost

# logrotate
logrotate

# novnc
novnc

# sudo
sudo

# config files

# net-snmp
net-snmp-utils
net-snmp-libs
net-snmp-python

# openldap
openldap
openldap-servers
openldap-clients

# openvswitch
openvswitch

# libevent
libevent

# tpm2-tools
tpm2-tools

# audit

# kernel
kernel
kernel-tools
kernel-tools-libs
perf
python-perf

# puppet
puppet

# systemd
systemd

# tboot
tboot

# memcached
memcached

# kubernetes
kubernetes
kubernetes-master
kubernetes-node
kubernetes-kubeadm
kubernetes-client

# resource-agents
resource-agents


# haproxy
haproxy


# iptables

# python-psycopg2
python-psycopg2

# dnsmasq
dnsmasq
dnsmasq-utils

# parted
parted

# python-keyring
python-keyring

# grub2
grub2-tools
grub2-efi-x64-modules

# kernel-rt
kernel-rt
kernel-rt-kvm
kernel-rt-tools

# mellanox drivers
rdma-core
mlnx-ofa_kernel-modules
mlnx-ofa_kernel-rt-modules


# python2-ruamel-yaml
python2-ruamel-yaml


# redfish tool
Redfishtool

# kvm-timer-advance (AIO and worker nodes only)
kvm-timer-advance
