# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#


# ceph
ceph
ceph-radosgw
ceph-fuse


# qemu-kvm-ev
qemu-kvm-ev
qemu-img-ev
qemu-kvm-tools-ev


# libvirt
libvirt
libvirt-docs
libvirt-daemon
libvirt-daemon-config-network
libvirt-daemon-config-nwfilter
libvirt-daemon-driver-network
libvirt-daemon-driver-nwfilter
libvirt-daemon-driver-nodedev
libvirt-daemon-driver-secret
libvirt-daemon-driver-storage
libvirt-daemon-driver-qemu
libvirt-daemon-driver-lxc
libvirt-client


# python-ryu
python3-ryu
python3-ryu-common

# lldpd
lldpd

# tss2
tss2


# libtpms
libtpms

# python-3parclient
python3-3parclient

# python-lefthandclient
python3-lefthandclient

# docker-distribution
docker-distribution

# helm
helm

# armada
armada

# rpm
rpm-plugin-systemd-inhibit

# dpkg
dpkg

# ldapscripts
ldapscripts

# drbd
drbd
drbd-utils
drbd-udev
drbd-pacemaker
drbd-heartbeat
drbd-bash-completion


# initscripts
initscripts

# setup
setup

# nss-pam-ldapd
nss-pam-ldapd


# nfs-utils series package

# dhcp
dhcp-server
dhcp-client

# openssh
openssh
openssh-clients
openssh-server

# facter
facter

# vim
vim-enhanced

# python
#python

# libvirt-python
python3-libvirt

# lighttpd
lighttpd
lighttpd-fastcgi
#lighttpd-mod_geoip
lighttpd-mod_mysql_vhost

# logrotate
logrotate

# novnc
novnc

# sudo
sudo

# config files

# net-snmp
net-snmp-utils
net-snmp-libs
#net-snmp-python

# openldap
openldap
openldap-servers
openldap-clients

# openvswitch
openvswitch

# libevent
libevent

# tpm2-tools
tpm2-tools

# audit

# puppet
puppet

# systemd
systemd

# tboot
tboot

# memcached
memcached

# kubernetes
kubernetes
kubernetes-master
kubernetes-node
kubernetes-kubeadm
kubernetes-client
containerd
k8s-pod-recovery

# resource-agents
resource-agents


# haproxy
haproxy


# iptables

# python-psycopg2
python3-psycopg2

# dnsmasq
dnsmasq
dnsmasq-utils

# parted
parted

# python-keyring
python3-keyring

# grub2
grub2-tools
grub2-efi-x64-modules

# python3-ruamel-yaml
python3-ruamel-yaml


# redfish tool
Redfishtool

# kvm-timer-advance (AIO and worker nodes only)
kvm-timer-advance

# aws packages for interacting with amazon aws registry
# botocore is an unspecified requirement of boto3
python3-botocore
python3-boto3
