# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#



# lldpd
lldpd

# tss2
tss2


# libtpms
libtpms

# python-3parclient
python-3parclient

# python-lefthandclient
python-lefthandclient

# docker-distribution
docker-distribution

# helm
helm

# armada
armada

# rpm
rpm-plugin-systemd-inhibit

# dpkg
dpkg

# ldapscripts
ldapscripts

# drbd
drbd
drbd-utils
drbd-udev
drbd-pacemaker
drbd-heartbeat
drbd-bash-completion


# initscripts
initscripts

# setup
setup

# nss-pam-ldapd
nss-pam-ldapd


# nfs-utils series package

# dhcp
dhcp
dhclient

# openssh
openssh
openssh-clients
openssh-server

# facter
facter

# vim
vim-enhanced

# python
python

# libvirt-python
python2-libvirt

# lighttpd
lighttpd
lighttpd-fastcgi
lighttpd-mod_geoip
lighttpd-mod_mysql_vhost

# linuxptp
linuxptp

# logrotate
logrotate

# novnc
novnc

# sudo
sudo

# config files

# openldap
openldap
openldap-servers
openldap-clients

# openvswitch
openvswitch

# libevent
libevent

# tpm2-tools
tpm2-tools

# audit

# puppet
puppet

# systemd
systemd

# tboot
tboot

# memcached
memcached

# kubernetes
kubernetes-unversioned
kubernetes-1.21.8-node
kubernetes-1.21.8-kubeadm
kubernetes-1.21.8-client
kubernetes-1.22.5-node
kubernetes-1.22.5-kubeadm
kubernetes-1.22.5-client
kubernetes-1.23.1-node
kubernetes-1.23.1-kubeadm
kubernetes-1.23.1-client
containerd
k8s-pod-recovery
k8s-cni-cache-cleanup
containernetworking-plugins
bond-cni

# resource-agents
resource-agents

# isolcpus device plugin for K8s
isolcpus-device-plugin

# kubectl-cert-manager
kubectl-cert-manager

# haproxy
haproxy


# iptables

# python-psycopg2
python-psycopg2

# dnsmasq
dnsmasq
dnsmasq-utils

# parted
parted

# python-keyring
python-keyring

# grub2
grub2-tools
grub2-efi-x64-modules

# python2-ruamel-yaml
python2-ruamel-yaml


# redfish tool
Redfishtool

# kvm-timer-advance (AIO and worker nodes only)
kvm-timer-advance

# aws packages for interacting with amazon aws registry
# botocore is an unspecified requirement of boto3
python2-botocore
python-boto3

# Pf bbdev configuration tool for ACC100 (Mt. Bryce)
pf-bb-config

# kexec-tools
kexec-tools

iproute-tc
