# List of packages to be included/installed in ISO

facter
kdump-tools
puppet
drbd-utils
parted
libvirt0
libvirt-clients
libvirt-daemon
libvirt-daemon-driver-lxc
libvirt-daemon-driver-qemu
libvirt-daemon-driver-storage-gluster
libvirt-login-shell
lvm2
trident-installer
iputils-arping
iputils-ping
iputils-tracepath
qemu-block-extra
qemu-guest-agent
qemu-system-common
qemu-system-data
qemu-system-x86
