#!/bin/bash

LOCAL_DIR=$1
PKGNAME=ostree
BASE_DIR=$STX_GIT_SRC_DIR/
SRC_DIR=$BASE_DIR/$PKGNAME
META_DIR=$BASE_DIR/meta-lat/data/debian/$PKGNAME/metadata_patches
PATCHES_DIR=$BASE_DIR/meta-lat/data/debian/$PKGNAME/source_patches
cp -Lr $SRC_DIR $LOCAL_DIR
cd $LOCAL_DIR
for patch in `ls ${META_DIR}/*.patch`; do
	patch -p1 < $patch || exit 1
done
mkdir debian/patches/lat
cp -f ${PATCHES_DIR}/*.patch debian/patches/lat/
