[process]
process  = ovs-access-monitor
service  = ovs-access-monitor
pidfile  = /var/run/ovs-access-monitor.pid
style    = lsb            ; ocf or lsb
severity = major          ; minor, major, critical
restarts = 3              ; restarts before error assertion
interval = 5              ; number of seconds to wait between restarts
debounce = 20             ; number of seconds to wait before degrade clear
startuptime = 5           ; seconds to wait after process start before monitoring
