#!/bin/bash
#
# chkconfig: 2345 50 50
#

### BEGIN INIT INFO
# Provides:             qemu_clean
# Short-Description:    Clean up stale unix sockets for qemu
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
### END INIT INFO



start()
{
    cd /var/lib/libvirt/qemu
    rm -f instance-*.monitor
    rm -f cgcs.heartbeat.*
}

stop ()
{
    # Nothing to do
    return
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
