#!/bin/bash

LOCAL_DIR=$1
PKGNAME=mttyexec
META_LAT_TARBALL=meta-lat.tar.gz
META_LAT=meta-lat

mkdir -p ${META_LAT}
tar xzvf ${META_LAT_TARBALL} --strip-components 1 -C ${META_LAT}

BASE_DIR=$(realpath ${META_LAT})
SRC_DIR=${BASE_DIR}/data/debian/${PKGNAME}/sources
DEB_DIR=${BASE_DIR}/data/debian/${PKGNAME}/metadata/debian
cp -Lr ${SRC_DIR} ${LOCAL_DIR}
cp -Lr ${DEB_DIR} ${LOCAL_DIR}
