#!/bin/bash

LOCAL_DIR=$1
PKGNAME=watchdog
META_LAT_TARBALL=meta-lat.tar.gz
META_LAT=meta-lat

mkdir -p ${META_LAT}
tar xzvf ${META_LAT_TARBALL} --strip-components 1 -C ${META_LAT}

BASE_DIR=$(realpath ${META_LAT})
PKG_DIR=${BASE_DIR}/data/debian/${PKGNAME}
META_DIR=${PKG_DIR}/metadata_patches
SRC_DIR=${PKG_DIR}/sources

MAJOR_VER="5.16"
REVISION="1"
PATCH_VER="1"
VER=${MAJOR_VER}-${PATCH_VER}.${REVISION}
DSC_FILE=${PKGNAME}_${VER}.dsc

dpkg-source -x ${DSC_FILE}
cd ${LOCAL_DIR}
for patch in $(ls ${META_DIR}/*.patch); do
	patch -p1 < $patch || exit 1
done
cp ${SRC_DIR}/* .
