.TH mount.fuse.ceph "8" "March 2014" "ceph-fuse" "User Commands"
.SH NAME
mount.fuse.ceph \- wrapper around ceph-fuse
.SH DESCRIPTION
Helper to mount ceph-fuse from /etc/fstab. To use, add an entry like:

.nf
#  DEVICE                                              PATH         TYPE      OPTIONS
  mount.fuse.ceph#conf=/etc/ceph/ceph.conf,id=admin   /mnt/ceph     fuse     _netdev,noatime,allow_other     0    0
  mount.fuse.ceph#conf=/etc/ceph/foo.conf,id=myuser   /mnt/ceph2    fuse     _netdev,noatime,allow_other     0    0
.fi

where the device field is a comma-separated list of options to pass on
the command line.  The examples above, for example, specify that
ceph-fuse will authenticated as client.admin and client.myuser
(respectively), and the second example also sets the "conf" option to
"/etc/ceph/foo.conf" via the ceph-fuse command line. Any valid
ceph-fuse option can be passed in this way.

.SH OPTIONS
.TP 4
\fB\-\-conf\fR
path to ceph cponfiguration file, usually "/etc/ceph/ceph.conf"
.TP 4
\fB\-\-id\fR
user name

.SH SEE ALSO
.TP
\fBceph-fuse\fP(8)
