#!/bin/bash
# Devstack settings

# This plugin enables StarlingX stx-integ services and follows the
# DevStack plugin contract:
# https://docs.openstack.org/devstack/latest/plugins.html#plugin-sh-contract

# Services
# platform-util

# Defaults
# --------

STX_INTEG_NAME=stx-integ

######### Plugin Specific ##########
enable_service $STX_INTEG_NAME

# This must not use any variables to work properly in OpenStack's DevStack playbook
define_plugin stx-integ
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires stx-integ stx-update

# Initial source of lib script
source $DEST/stx-integ/devstack/lib/stx-integ
