---
debname: python3-kubernetes
debver: 35.0.0
dl_path:
    name: python3-kubernetes.35.0.0.tar.gz
    url: https://github.com/kubernetes-client/python/archive/refs/tags/v35.0.0.tar.gz
    sha256sum: 766fa697d4b2a7ef2616c8b720fb4d4b5aa6f48c584cd4ed9411648b098b7d2d
revision:
    dist: $STX_DIST
    GITREVCOUNT:
        BASE_SRCREV: 310ac64ec5ec83206103422ef6820282acb3f472
        SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/python3-kubernetes
