---
debname: flux2-charts
debver: 2.18.2-0
src_path: files
dl_path:
  name: flux2-2.18.2.tar.gz
  url: https://github.com/fluxcd-community/helm-charts/archive/refs/tags/flux2-2.18.2.tar.gz
  sha256sum: ea06030676c560d07b44f11b47a03c426d9ec0ed10ef11c8a7eff406a3612997
src_files:
  - files/Makefile
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
