#!/bin/bash

LOCAL_DIR=$1
PKGNAME=watchdog
BASE_DIR=${STX_GIT_SRC_DIR}
PKG_DIR=${BASE_DIR}/meta-lat/data/debian/${PKGNAME}
META_DIR=${PKG_DIR}/metadata_patches
SRC_DIR=${PKG_DIR}/sources
BASE_URL=https://snapshot.debian.org/archive/debian/20200424T151944Z/pool/main/w/${PKGNAME}
MAJOR_VER="5.16"
REVISION="1"
VER=${MAJOR_VER}-${REVISION}
DSC_FILE=${PKGNAME}_${VER}.dsc
dget -x ${BASE_URL}/${DSC_FILE}
if [ $? != 0 ]; then
	echo "Fail to download ${BASE_URL}/${DSC_FILE}"
	exit -1
fi
cd ${LOCAL_DIR}
for patch in $(ls ${META_DIR}/*.patch); do
	patch -p1 < $patch || exit 1
done
cp ${SRC_DIR}/* .
