---
debname: puppet-module-puppetlabs-firewall
debver: 8.1.7-1
dl_path:
  name: puppet-module-puppetlabs-firewall-8.1.7-1.tar.gz
  url: https://salsa.debian.org/puppet-team/puppet-module-puppetlabs-firewall/-/archive/debian/8.1.7-1/puppet-module-puppetlabs-firewall-debian-8.1.7-1.tar.gz
  md5sum: 04f476cac1af6580aefa530ab146b96b
  sha256sum: f2e68cde2254053dd462457920e745702fd53f96973bc03fb5aa4243d57d2ab1
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
