#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})

mkdir ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download and extract helm source package.
CM_SOURCE=$(realpath ${STX_MIRROR}/downloads/chartmuseum-0.12.0.tar.gz)
CM_EXEC=$(realpath ${STX_MIRROR}/downloads/chartmuseum-v0.12.0-amd64)
cp ${CM_SOURCE} ${PKG_BUILD_ROOT}
cp ${CM_EXEC} ${PKG_BUILD_ROOT}
