.TH ceph-crush-location "1" "April 2014" "ceph-crush-location" "User Commands"
.SH NAME
ceph-crush-location \- get CRUSH location
.SH DESCRIPTION
Generate a CRUSH location for the given entity

The CRUSH location consists of a list of key=value pairs, separated
by spaces, all on a single line.  This describes where in CRUSH
hierarhcy this entity should be placed.

.SH OPTIONS
.TP 4
\fB\-\-cluster\fR <clustername>
name of the cluster (see /etc/ceph/$cluster.conf)
.TP 4
\fB\-\-type\fR <osd|mds|client>
daemon/entity type
.TP 4
\fB\-\-id\fR <id>
id (osd number, mds name, client name)

.SH SEE ALSO
.TP
\fBceph-conf\fP(8)
