#!/bin/bash
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. The ASF licenses this
# file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

mkdir -p "$1"

# Extract source code (removes efitools-1.9.2/ prefix)
tar xzf efitools_1.9.2.orig.tar.gz --strip-components=1 -C "$1"
if [ $? -ne 0 ]
then
    echo "tar failed: orig source!"
    exit 1
fi

tar xvf efitools_1.9.2-3.5.debian.tar.xz
if [ $? -ne 0 ]
then
    echo "tar failed: debian source!"
    exit 1
fi

mv debian/ "$1"
cp -r ./local_debian/uefi_sb_keys ./"$1"/debian/
cp "${MY_REPO}"/public-keys/tis-boot.crt ./"$1"/debian/uefi_sb_keys/
