#!/bin/bash
set -x
LOCAL_DIR=$1
PKGNAME=initramfs-ostree
BASE_DIR=$STX_GIT_SRC_DIR/meta-lat/data/debian
SRC_DIR=$BASE_DIR/$PKGNAME/sources
DEB_DIR=$BASE_DIR/$PKGNAME/metadata/debian
cp -Lr $SRC_DIR $LOCAL_DIR
cp -Lr $DEB_DIR $LOCAL_DIR
