#! /bin/sh
#
# Copyright (c) 2013-2014 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

### BEGIN INIT INFO
# Provides:          uexportfs
# Default-Start:     3
# Default-Stop:      
# Short-Description: Used to remove all exported filesystems on a boot
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

exportfs -r > /dev/null 2>&1

: exit 0
