---
debname: runc
debver: 1.4.2
src_path: null
dl_files:
  runc.amd64:
    topdir: null
    url: https://github.com/opencontainers/runc/releases/download/v1.4.2/runc.amd64
    sha256sum: ac8a90f9e225bb9322189937b230cdc5478d5753f0e31e1bda98a5cf06bd9539
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: 1bbcf7596b4e73481ebbad6ef0ae46aa9ceb9bbc
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/runc
