---
debname: crane
debver: 0.21.5
src_path: null
dl_files:
  go-containerregistry_Linux_x86_64.tar.gz:
    topdir: null
    url: https://github.com/google/go-containerregistry/releases/download/v0.21.5/go-containerregistry_Linux_x86_64.tar.gz
    sha256sum: 9f823ae5ee25803161110f957b5fd4538f714d40cdf25dacb4914fefafd246bf
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: 0e30b2fcafecba2680f89819da31fd6d5283433a
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/crane
