---
debname: crane
debver: 0.20.1
src_path: null
dl_files:
  go-containerregistry_Linux_x86_64.tar.gz:
    topdir: null
    url: https://github.com/google/go-containerregistry/releases/download/v0.20.7/go-containerregistry_Linux_x86_64.tar.gz
    sha256sum: 8ef3564d264e6b5ca93f7b7f5652704c4dd29d33935aff6947dd5adefd05953e
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: 5f1d2d055db669949812fc7a39e47de85d24634d
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/crane
