#!/bin/bash

#
# Copyright (c) 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

. /usr/sbin/customize-banner

install_banner_files

# recreate /etc/motd
/usr/sbin/motd-update

exit 0
