#!/bin/bash

#
# Copyright (c) 2014, 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

MOTD_FILE=${MOTD_FILE:-"/etc/motd"}
MOTD_PATH=${MOTD_PATH:-"/etc/motd.d"}
MOTD_TAG=${MOTD_TAG:-"motd-update"}

if [ -d ${MOTD_PATH} ]; then
    run-parts ${MOTD_PATH} 1>${MOTD_FILE}
fi
