#!/bin/sh

#
# Copyright (c) 2014-2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# motd.head is reserved for the admin to prepend 
# static information to a dynamically generated
# /etc/motd.
#
# To add dynamic information, add a numbered
# script to /etc/motd.d/

[ -f /etc/motd.head ] && cat /etc/motd.head || true
