#!/bin/sh
#
# Copyright (c) 2013-2014, 2016 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#


### BEGIN INIT INFO
# Provides:          ceph-manager
# Required-Start:    $ceph
# Required-Stop:     $ceph
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Daemon for polling ceph status
# Description:       Daemon for polling ceph status
### END INIT INFO

DESC="ceph-manager"
DAEMON="/usr/bin/ceph-manager"
RUNDIR="/var/run/ceph"
PIDFILE=$RUNDIR/$DESC.pid

CONFIGFILE="/etc/sysinv/sysinv.conf"
LOGFILE="/var/log/ceph-manager.log"

start() 
{
    if [ -e $PIDFILE ]; then
        PIDDIR=/prod/$(cat $PIDFILE)
        if [ -d ${PIDFILE} ]; then
            echo "$DESC already running."
            exit 0
        else
            echo "Removing stale PID file $PIDFILE"
            rm -f $PIDFILE
        fi
    fi

    echo -n "Starting $DESC..."
    mkdir -p $RUNDIR
    start-stop-daemon --start --quiet \
        --pidfile ${PIDFILE} --exec ${DAEMON} \
        --make-pidfile --background \
        -- --log-file=$LOGFILE --config-file=$CONFIGFILE

    if [ $? -eq 0 ]; then
        echo "done."
    else
        echo "failed."
        exit 1
    fi
}

stop()
{
    echo -n "Stopping $DESC..."
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 60
    if [ $? -eq 0 ]; then
        echo "done."
    else
        echo "failed."
    fi
    rm -f $PIDFILE
}

status()
{
    pid=`cat $PIDFILE 2>/dev/null`
    if [ -n "$pid" ]; then
        if ps -p $pid &> /dev/null ; then
            echo "$DESC is running"
            exit 0
        else
            echo "$DESC is not running but has pid file"
            exit 1
        fi
    fi
    echo "$DESC is not running"
    exit 3
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload|reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|force-reload|restart|reload|status}"
        exit 1
        ;;
esac

exit 0
