#!/bin/bash
#
# /etc/dhclient-enter-hooks
#
# This file is sourced by /sbin/dhclient-script.
#

# Select wrs-install-uuid from ipv4 or ipv6
if [ -n "$new_dhcp6_wrs_install_uuid" ]; then
  wrs_install_uuid=$new_dhcp6_wrs_install_uuid
else
  wrs_install_uuid=$new_wrs_install_uuid
fi

# Enforce wrs-install-uuid on management and infrastrucure interfaces
source /etc/platform/platform.conf
if [ -n "$wrs_install_uuid" ]; then
  if [ "$nodetype" == "controller" ]; then
    source /etc/build.info
    file="/www/pages/feed/rel-$SW_VERSION/install_uuid"
    INSTALL_UUID=$(cat "$file")
  fi
  if [ "$INSTALL_UUID" != "$wrs_install_uuid" ]; then
     exit_status=1
   fi
elif [ "$interface" == "$management_interface" -o \
       "$interface" == "$infrastructure_interface" ]; then
  if [ "$nodetype" != "controller" -o \
       -e "/etc/platform/.initial_config_complete" ]; then
     exit_status=1
  fi
fi
