debver: 1.32.13
dl_path:
  name: kubernetes-1.32.13.tar.gz
  url: https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.32.13.tar.gz
  sha256sum: 3b48c21be36b5d7e387dcd7bd1914b223b3aeb55ae7ded4cdc5244dd943accc1
revision:
  dist: ${STX_DIST}
  GITREVCOUNT:
    BASE_SRCREV: 92c7fac2b8a056d844c95e3b76044b8a104264f7
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/kubernetes-1.32.13
