#! /bin/bash

sysctl -w vm.nr_hugepages=1024
mkdir -p /dev/hugepages
mount -t hugetlbfs -o pagesize=2M none /dev/hugepages

ovs-vsctl --no-wait set Open_vSwitch . "other_config:dpdk-init=true"
ovs-vsctl --no-wait set Open_vSwitch . "other_config:dpdk-lcore-mask=1"
ovs-vsctl --no-wait set Open_vSwitch . "other_config:dpdk-alloc-mem=512"

