#! /bin/bash

# update ovs-vswitchd.service

sed -i "/ExecStartPre=\/usr\/bin\/ovs_dpdk_config_pre/d" /usr/lib/systemd/system/ovs-vswitchd.service
sed -i "/\[Service\]/a ExecStartPre=/usr/bin/ovs_dpdk_config_pre" /usr/lib/systemd/system/ovs-vswitchd.service

sed -i "/ExecStartPost=\/usr\/bin\/ovs_dpdk_config_post/d" /usr/lib/systemd/system/ovs-vswitchd.service
sed -i "/\[Service\]/a ExecStartPost=/usr/bin/ovs_dpdk_config_post" /usr/lib/systemd/system/ovs-vswitchd.service

# update neutron-openvswitch-agent.servic
sed -i "s#ExecStart=.*#ExecStart=/usr/bin/neutron-openvswitch-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/openvswitch_agent.ini --log-file /var/log/neutron/openvswitch-agent.log#" /usr/lib/systemd/system/neutron-openvswitch-agent.service

sed -i "s#User=.*#User=root#" /usr/lib/systemd/system/neutron-openvswitch-agent.service

sed -i "/Requires=ovs-vswitchd.service/d" /usr/lib/systemd/system/neutron-openvswitch-agent.service
sed -i "/\[Unit\]/a Requires=ovs-vswitchd.service" /usr/lib/systemd/system/neutron-openvswitch-agent.service

sed -i "s#After=syslog.target#After=ovs-vswitchd.service syslog.target#" /usr/lib/systemd/system/neutron-openvswitch-agent.service

#sed -i "/ExecStartPre=\/usr\/bin\/ovs_dpdk_config_post/d" /usr/lib/systemd/system/neutron-openvswitch-agent.service
#sed -i "/\[Service\]/a ExecStartPre=/usr/bin/ovs_dpdk_config_post" /usr/lib/systemd/system/neutron-openvswitch-agent.service

#work around
sed -i "/Requires=openvswitch.service neutron-openvswitch-agent.service neutron-l3-agent.service/d" /usr/lib/systemd/system/nova-compute.service
sed -i "/\[Unit\]/a Requires=openvswitch.service neutron-openvswitch-agent.service neutron-l3-agent.service" /usr/lib/systemd/system/nova-compute.service

# update neutron-l3-agent.service
sed -i "s#ExecStart=.*#ExecStart=/usr/bin/neutron-l3-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/l3_agent.ini --log-file /var/log/neutron/l3-agent.log#" /usr/lib/systemd/system/neutron-l3-agent.service

sed -i "s#User=.*#User=root#" /usr/lib/systemd/system/neutron-l3-agent.service
sed -i "s#After=syslog.target#After=neutron-openvswitch-agent.service syslog.target#" /usr/lib/systemd/system/neutron-l3-agent.service

