#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG="openstack-helm-infra"
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
mkdir -p ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download armada-helm-toolkit helm source package.
ARMADA_HELM_TOOLKIT_PKG="openstack-helm-infra-c9d6676bf9a5aceb311dc31dadd07cba6a3d6392.tar.gz"
ARMADA_HELM_TOOLKIT_SRC_PATH=$(realpath ${STX_MIRROR}/downloads/${ARMADA_HELM_TOOLKIT_PKG})
cp ${ARMADA_HELM_TOOLKIT_SRC_PATH} ${PKG_BUILD_ROOT}

# Extract the armada tar file.
tar xfz ${ARMADA_HELM_TOOLKIT_PKG}
cp -pr ${PKG}/* ${PKG_BUILD_ROOT}
