# increment this every release
API_VERSION := "1.6.0"

build:
	@git status > /dev/null ; \
	if [ $$? -ne 0 ] ; then \
		echo CREATING DUMMY GIT ; \
        git init ; \
	fi

	mvn clean generate-sources dependency:go-offline -Dmaven.repo.local=./mvn.repo/
	cd mvn.repo && tar -czvf ../mvn.repo.tgz . && cd ..

	mkdir -p target/wrs-restapi-doc-$(API_VERSION)/
	cp rest-api-usage-example.pdf target/wrs-restapi-doc-$(API_VERSION)/
	cp -R api-ref-guides/target/docbkx/pdf target/wrs-restapi-doc-$(API_VERSION)/
	cp -R api-ref/target/docbkx/html target/wrs-restapi-doc-$(API_VERSION)/
	cd target; tar -czvf ../wrs-restapi-doc-$(API_VERSION).tgz wrs-restapi-doc-$(API_VERSION)
	@echo 'wrs-restapi-doc-$(API_VERSION).tgz' is ready

clean:
	mvn clean -o -Dmaven.repo.local=./mvn.repo/
	rm -f wrs-restapi-doc-*.tgz
	rm -rf target
	
	rm -rf mvn.repo
